// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBYu5LV_NpiD1ZV5k1EtUHFOerV8fhdkg',
    appId: '1:90318104187:web:f8a815967bb0735b69e4de',
    messagingSenderId: '90318104187',
    projectId: 'instagram-clone-6390e',
    authDomain: 'instagram-clone-6390e.firebaseapp.com',
    storageBucket: 'instagram-clone-6390e.appspot.com',
    measurementId: 'G-EHTSTGD1PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDgnen9oYiP3156w6hqTT6W0icJ4m1Sog',
    appId: '1:90318104187:android:66468bb06d8e08c669e4de',
    messagingSenderId: '90318104187',
    projectId: 'instagram-clone-6390e',
    storageBucket: 'instagram-clone-6390e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaUGT5BanTtGLyzozx6vVNYZmVtbb_D14',
    appId: '1:90318104187:ios:68da0780d2b86be169e4de',
    messagingSenderId: '90318104187',
    projectId: 'instagram-clone-6390e',
    storageBucket: 'instagram-clone-6390e.appspot.com',
    iosClientId: '90318104187-3nfvrnmuir3aguh9m47lfc2r3to5o823.apps.googleusercontent.com',
    iosBundleId: 'com.instagramclone.instagramClone',
  );
}
